/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PrincipalFrm.java
 *
 * Created on 07/05/2012, 05:19:22 PM
 */

package com.lightproducts.proyecto.frm;

/**
 *
 * @author alumno
 */
public class PrincipalFrm extends javax.swing.JFrame {

    /** Creates new form Principal */
    public PrincipalFrm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ToolBar = new javax.swing.JToolBar();
        btnFactura = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnCllientes = new javax.swing.JButton();
        btnVendedores = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        barraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemNuevo = new javax.swing.JMenuItem();
        itemImprimir = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemSalir = new javax.swing.JMenuItem();
        menuMantenimiento = new javax.swing.JMenu();
        itemProductos = new javax.swing.JMenuItem();
        itemClientes = new javax.swing.JMenuItem();
        itemVendedores = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        itemAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        ToolBar.setRollover(true);

        btnFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/venta.png"))); // NOI18N
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });
        ToolBar.add(btnFactura);

        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/product.png"))); // NOI18N
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        ToolBar.add(btnProductos);

        btnCllientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cliente.png"))); // NOI18N
        btnCllientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCllientesActionPerformed(evt);
            }
        });
        ToolBar.add(btnCllientes);

        btnVendedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/vendedor.png"))); // NOI18N
        btnVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendedoresActionPerformed(evt);
            }
        });
        ToolBar.add(btnVendedores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuArchivo.setText("Archivo");
        menuArchivo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menuArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArchivoActionPerformed(evt);
            }
        });

        itemNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNuevoActionPerformed(evt);
            }
        });
        menuArchivo.add(itemNuevo);

        itemImprimir.setText("Imprimir");
        menuArchivo.add(itemImprimir);
        menuArchivo.add(jSeparator1);

        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(itemSalir);

        barraMenu.add(menuArchivo);

        menuMantenimiento.setText("Mantenimiento");
        menuMantenimiento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        itemProductos.setText("Productos...");
        itemProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProductosActionPerformed(evt);
            }
        });
        menuMantenimiento.add(itemProductos);

        itemClientes.setText("Clientes...");
        itemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClientesActionPerformed(evt);
            }
        });
        menuMantenimiento.add(itemClientes);

        itemVendedores.setText("Vendedores...");
        itemVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVendedoresActionPerformed(evt);
            }
        });
        menuMantenimiento.add(itemVendedores);

        barraMenu.add(menuMantenimiento);

        menuAyuda.setText("Ayuda");
        menuAyuda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        itemAcerca.setText("Acerca de...");
        itemAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAcercaActionPerformed(evt);
            }
        });
        menuAyuda.add(itemAcerca);

        barraMenu.add(menuAyuda);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(ToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
        FacturaFrm n=new FacturaFrm();
        jDesktopPane1.add(n);
        n.show();
    }//GEN-LAST:event_btnFacturaActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        ProductosFrm n=new ProductosFrm();
        jDesktopPane1.add(n);
        n.show();
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnCllientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCllientesActionPerformed
        ClientesFrm n=new ClientesFrm();
        jDesktopPane1.add(n);
        n.show();
    }//GEN-LAST:event_btnCllientesActionPerformed

    private void btnVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendedoresActionPerformed
        VendedoresFrm n=new VendedoresFrm();
        jDesktopPane1.add(n);
        n.show();
    }//GEN-LAST:event_btnVendedoresActionPerformed

    private void menuArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuArchivoActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNuevoActionPerformed
        FacturaFrm n=new FacturaFrm();
        jDesktopPane1.add(n);
        n.show();
    }//GEN-LAST:event_itemNuevoActionPerformed

    private void itemProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProductosActionPerformed
        ProductosFrm n=new ProductosFrm();
        jDesktopPane1.add(n);
        n.show();
    }//GEN-LAST:event_itemProductosActionPerformed

    private void itemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClientesActionPerformed
        ClientesFrm n=new ClientesFrm();
        jDesktopPane1.add(n);
        n.show();
    }//GEN-LAST:event_itemClientesActionPerformed

    private void itemVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVendedoresActionPerformed
        VendedoresFrm n=new VendedoresFrm();
        jDesktopPane1.add(n);
        n.show();
    }//GEN-LAST:event_itemVendedoresActionPerformed

    private void itemAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcercaActionPerformed
        AcercaFrm n=new AcercaFrm();
        jDesktopPane1.add(n);
        n.show();
    }//GEN-LAST:event_itemAcercaActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar ToolBar;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton btnCllientes;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnVendedores;
    private javax.swing.JMenuItem itemAcerca;
    private javax.swing.JMenuItem itemClientes;
    private javax.swing.JMenuItem itemImprimir;
    private javax.swing.JMenuItem itemNuevo;
    private javax.swing.JMenuItem itemProductos;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuItem itemVendedores;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuMantenimiento;
    // End of variables declaration//GEN-END:variables

}
